### ISSUE TITLE
Get it working with MacOS Catalyst?

### ISSUE THREAD

**Issue by robertherber** [thefunbots/react-native-pointer-interactions#14]
I'm trying to get this working on MacOS Catalyst (on the M1), but can't seem to get it working. [According to Apple's docs it looks like it should be possible](https://developer.apple.com/documentation/uikit/uipointerinteraction) but I'm starting to have my doubts. It doesn't crash or anything - it just doesn't work.

Any ideas?

**Comment by sonnysantino** [comment]
I'm not sure that is even possible, looks like something specific for iPad only, do you know any mac app that use this?

**Comment by robertherber** [comment]
I've skimmed through lots of Apple docs and I can't find clear indication on whether it's possible with the UIPointerInteraction API. It would make sense if Apple provided one API for both. I see many apps using hover effects on Mac - but the hover effect is slightly different (which kinda makes sense).

This is another API that might work on both: https://developer.apple.com/documentation/uikit/uihovergesturerecognizer - maybe this could be used to provide a simple fallback?

**Comment by sonnysantino** [comment]
For what i understand this will only give the on hover event, having you to recreate the nice effects apple provides on ipad

**Comment by robertherber** [comment]
Yeah, that’s my understanding as well.
